    using System.ComponentModel;

namespace Pantec.Wrapper.Entities.Models
{
    public enum SignalNameType
    {
        [Description("Signal name not set")]
        NotSet,
        [Description("System autogenerated signal name")]
        System,
        [Description("Signal name set by user")]
        User
    }
}